ModaMiguelao.Web/ViewModels/ProductViewModel.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Web;

namespace ModaMiguelao.Web.ViewModels
{
    public class ProductViewModel
    {
        [Key]
        public long Id { get; set; }

        //TODO - tamanho maximo

        [DisplayName("Nome")]
        [Required(ErrorMessage = "Preencha o campo nome")]
        [MaxLength(250, ErrorMessage = "Máximo {0} caracteres")]
        [MinLength(2, ErrorMessage = "Mínimo {0} caracteres")]
        public string Name { get; set; }

        [DisplayName("Descrição")]
        [Required(ErrorMessage = "Preencha o campo Descrição")]
        [DataType(DataType.MultilineText)]
        [MaxLength(100, ErrorMessage = "Máximo {0} caracteres")]
        public string Description { get; set; }

        [DisplayName("Valor")]
        [DataType(DataType.Currency)]
        [Range(0.01, double.MaxValue, ErrorMessage ="Valor fora do intervalo")]
        [Required(ErrorMessage = "Preencha o campo valor")]
        public decimal Value { get; set; }

        [Required(ErrorMessage = "Preencha o campo Categoria")]
        [DisplayName("Categoria")]
        public string Category { get; set; }

        [DisplayName("Disponível?")]
        public bool Available { get; set; }

        [Required(ErrorMessage = "Preencha o campo Imagem")]
        [DisplayName("Imagem")]
        public string ImagePath { get; set; }

        public HttpPostedFileBase Image { get; set; }


        //public long ClientId { get; set; }
        //public virtual ClientViewModel Client { get; set; }
    }
}

ModaMiguelao.Web/Areas/Manager/Controllers/ProductController.cs
using AutoMapper;
using ModaMiguelao.Application.Interfaces;
using ModaMiguelao.Domain.Entities;
using ModaMiguelao.Web.ViewModels;
using System.Collections.Generic;
using System.Web.Mvc;

namespace ModaMiguelao.Web.Areas.Manager.Controllers
{
    //[Authorize]
    public class ProductController : Controller
    {
        private IProductApplicationService ProductApplication { get; }

        public ProductController(IProductApplicationService productApplication)
        {
            ProductApplication = productApplication;
        }

        public ActionResult Index()
        {
            var products = ProductApplication.GetAll();
            var productsVM = Mapper.Map<IEnumerable<Product>, IEnumerable<ProductViewModel>>(products);

            return View(productsVM);
        }

        public ActionResult Create()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(ProductViewModel productVM)
        {
            if (ModelState.IsValid)
            {
                var product = Mapper.Map<ProductViewModel, Product>(productVM);
                this.ProductApplication.Add(product);

                TempData["message"] = string.Format("{0} foi criado!", product.Name);
                return RedirectToAction("Index");
            }

            return View(productVM);
        }


        public ViewResult Edit(long id)
        {
            var product = this.ProductApplication.GetById(id);
            var productVM = Mapper.Map<Product, ProductViewModel>(product);

            return View(productVM);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(ProductViewModel productVM)
        {
            if (ModelState.IsValid)
            {
                if(productVM.Image!= null)
                {
                    //faz upload da imagem
                }

                var product = Mapper.Map<ProductViewModel, Product>(productVM);
                this.ProductApplication.Update(product);

                TempData["message"] = string.Format("{0} foi alterado!", product.Name);
                return RedirectToAction("Index");
            }

            return View(productVM);
        }

        public ViewResult Delete(long id)
        {
            var product = this.ProductApplication.GetById(id);
            var productVM = Mapper.Map<Product, ProductViewModel>(product);

            return View(productVM);
        }


        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(long id)
        {
            var product = ProductApplication.GetById(id);
            this.ProductApplication.Remove(product);

            TempData["message"] = string.Format("{0} foi removido!", product.Name);
            return RedirectToAction("Index");
        }




        //[HttpPost]
        //public JsonResult Edit(ProductViewModel productVM)
        //{
        //    string mensagem = string.Empty;
        //    return Json(mensagem, JsonRequestBehavior.AllowGet);
        //}

        //<input type="submit" class = "btn btn-default btn-xs" value="Excluir" id="@item.Id" name="@item.Nome" />
    }
}

ModaMiguelao.Web/Controllers/ProductController.cs
using AutoMapper;
using ModaMiguelao.Application.Interfaces;
using ModaMiguelao.Domain.Entities;
using ModaMiguelao.Web.PartialControllers;
using ModaMiguelao.Web.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;


namespace ModaMiguelao.Web.Controllers
{
    //TODO - Remover o entity da view

    public class ProductController : Controller
    {
        private readonly IProductApplicationService _productApplication;

        public ProductController(IProductApplicationService productApplication)
        {
            _productApplication = productApplication;
        }


        //TODO - diferença entre view result e action result
        public ViewResult Index(string category, int page = 1)
        {
            int productsPerPage = 5;

            var productsDomain = _productApplication
                .GetAll()
                .Where(x => string.IsNullOrEmpty(category) || x.Category == category)
                .OrderBy(p => p.Name)
                .Skip((page - 1) * productsPerPage)
                .Take(productsPerPage);

            var paging = new PagingController()
            {
                CurrentPage = page,
                ItensPerPage = productsPerPage,
                TotalItens = _productApplication
                    .GetAll()
                    .Where(x => string.IsNullOrEmpty(category) || x.Category == category)
                    .Count()
            };

            ViewBag.Paging = paging;
            ViewBag.CurrentCategory = category;

            var productsVM = Mapper.Map<IEnumerable<Product>, IEnumerable<ProductViewModel>>(productsDomain);

            return View(productsVM);
        }

        public PartialViewResult Category(string category = null)
        {
            ViewBag.CurrentCategory = category;

            IEnumerable<string> categories = _productApplication
                .GetAll()
                .Select(x=> x.Category)
                .Distinct()
                .OrderBy(x => x);

            return PartialView(categories);
        }
    }
}

ModaMiguelao.Web/Areas/Manager/Views/Product/Create.cshtml
@model ModaMiguelao.Web.ViewModels.ProductViewModel

@using (Html.BeginForm("Create","Product", FormMethod.Post, new { encType = "multipart/form-data" }) )
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>ProductViewModel</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Value, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Value, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Value, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Category, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Category, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Category, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Available, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <div class="checkbox">
                @Html.EditorFor(model => model.Available)
                @Html.ValidationMessageFor(model => model.Available, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.ImagePath, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <div class="checkbox">
                @Html.EditorFor(model => model.ImagePath)
                @Html.ValidationMessageFor(model => model.ImagePath, "", new { @class = "text-danger" })
                @*<img class="img-thumbnail" />*@

            </div>
        </div>
    </div>


    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            @Html.ActionLink("Cancelar", "Index", null, new { @class = "btn btn-default" })
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
</div>
}

ModaMiguelao.Web/Areas/Manager/Views/Product/Delete.cshtml
@model ModaMiguelao.Web.ViewModels.ProductViewModel

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>ProductViewModel</h4>
    <hr />


    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Value)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Value)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Category)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Category)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Available)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Available)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        <div class="form-actions no-color">
            @Html.ActionLink("Cancelar", "Index", null, new { @class = "btn btn-default" })
            <input type="submit" value="Delete" class="btn btn-default" />
        </div>
    }
</div>

ModaMiguelao.Web/Areas/Manager/Views/Product/Edit.cshtml
@model ModaMiguelao.Web.ViewModels.ProductViewModel

@section scripts{
    @Scripts.Render("~/bundles/jqueryval")
}

<div class="panel">
    <div class="panel-heading">
        <h3>Alterar @Model.Name</h3>
    </div>

    @using (Html.BeginForm())
    {
        <div class="panel-body">
            @Html.AntiForgeryToken()
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.Id)

            <div class="form-group">
                @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label" })
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label" })
                @Html.TextAreaFor(model => model.Description, new { @class = "form-control", rows = 5 })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Value, htmlAttributes: new { @class = "control-label" })
                @Html.EditorFor(model => model.Value, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Value, "", new { @class = "text-danger" })
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Category, htmlAttributes: new { @class = "control-label" })
                @Html.EditorFor(model => model.Category, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Category, "", new { @class = "text-danger" })
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Available, htmlAttributes: new { @class = "control-label" })
                @Html.EditorFor(model => model.Available)
                @Html.ValidationMessageFor(model => model.Available, "", new { @class = "text-danger" })

            </div>

            @*<div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        @Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-default" })
                        <input type="submit" value="Save" class="btn btn-default" />
                    </div>
                </div>*@
        </div>
        <div class="panel-footer">
            @Html.ActionLink("Cancelar", "Index", null, new { @class = "btn btn-default" })
            <input type="submit" value="Save" class="btn btn-primary" />
        </div>
    }
</div>

ModaMiguelao.Web/Areas/Manager/Views/Product/Index.cshtml
@model IEnumerable<ModaMiguelao.Web.ViewModels.ProductViewModel>

@{
    ViewBag.Title = "Admin - Produtos";
}

<div class="panel panel-default">
    <div class="panel-heading">
        <h3>Moda Miguelão Produtos</h3>
    </div>
    <div class="panel-body">
        @Html.ActionLink("Novo", "Create", null, new { @class = "btn btn-default" })

        <table class="table table-striped table-condensed table-bordered">
            <thead>
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.Name)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Description)
                    </th>
                    <th class="text-right">
                        @Html.DisplayNameFor(model => model.Value)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Category)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Available)
                    </th>
                    <th></th>
                </tr>
            </thead>

            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.ActionLink(item.Name, "Edit", new { id = item.Id })
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Description)
                        </td>
                        <td class="text-right">
                            @Html.DisplayFor(modelItem => item.Value)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Category)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Available)
                        </td>
                        <td class="text-center">
                            @Html.ActionLink("Delete", "Delete", new { id = item.Id }, new { @class = "btn btn-default btn-xs" })
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>