ModaMiguelao.Web/ViewModels/ShoppingCartViewModel.cs
using ModaMiguelao.Domain.Entities;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace ModaMiguelao.Web.ViewModels
{
    public class ShoppingCartViewModel
    {
        public List<ShoppingCartItemViewModel> Itens { get; set; }

        [DataType(DataType.Currency)]
        [Range(typeof(decimal), "0", "999999999999")]
        public decimal Total { get; set; }
    }
}

ModaMiguelao.Web/Controllers/OrderController.cs
using AutoMapper;
using ModaMiguelao.Application.Interfaces;
using ModaMiguelao.Domain.Entities;
using ModaMiguelao.Web.ViewModels;
using System.Web.Mvc;

namespace ModaMiguelao.Web.Controllers
{
    public class OrderController : Controller
    {
        private IOrderApplicationService OrderApplication { get; }

        private IProductApplicationService ProductApplication { get; }

        public OrderController(IOrderApplicationService orderApplication, IProductApplicationService productApplication)
        {
            OrderApplication = orderApplication;
            ProductApplication = productApplication;
        }

        public ActionResult Index()
        {
            return View();
        }

        public ViewResult CloseOrder()
        {
            var orderVM = new OrderViewModel();
            var shoppingCart = GetShoppingCart();
            orderVM.ShoppingCart = Mapper.Map<ShoppingCart, ShoppingCartViewModel>(shoppingCart);

            return View(orderVM);
        }

        [HttpPost]
        public ViewResult CloseOrder(OrderViewModel orderVM)
        {
            var order = Mapper.Map<OrderViewModel, Order>(orderVM);

            if (ModelState.IsValid)
            {
                this.OrderApplication.CloseOrder(order);
                return View("CloseOrderSuccess");
            }

            return View(orderVM);
        }

        public ShoppingCart GetShoppingCart()
        {
            ShoppingCart _shoppingCart = (ShoppingCart)Session["ShoppingCart"];
            if (_shoppingCart == null)
                _shoppingCart = new ShoppingCart();

            return _shoppingCart;
        }
    }
}

ModaMiguelao.Web/Controllers/ShoppingCartController.cs
using AutoMapper;
using ModaMiguelao.Application.Interfaces;
using ModaMiguelao.Domain.Entities;
using ModaMiguelao.Web.PartialControllers;
using ModaMiguelao.Web.ViewModels;
using System;
using System.Linq;
using System.Web.Mvc;

namespace ModaMiguelao.Web.Controllers
{
    public class ShoppingCartController : Controller
    {
        private readonly IProductApplicationService _productApplication;

        public ShoppingCartController(IProductApplicationService productApplication)
        {
            _productApplication = productApplication;
        }

        public ViewResult Index(string returnUrl)
        {
            var _shoppingCart = GetShoppingCart();
            var shoppingCartVM = Mapper.Map<ShoppingCart, ShoppingCartViewModel>(_shoppingCart);

            ViewBag.returnUrl = returnUrl;
            ViewBag.urlRemoveitem = "/ShoppingCart/Remove/";
            ViewBag.Modal = new RemoveShoppingCartItemModalController();
            
            return View(shoppingCartVM);
        }

        public RedirectToRouteResult Add(long id, string returnUrl)
        {
            var product = _productApplication.GetById(id);

            if (product != null)
            {
                //ShoppingCart _shoppingCart = new ShoppingCart();
                var _shoppingCart = GetShoppingCart();

                _shoppingCart.AddItem(product);
                Session["ShoppingCart"] = _shoppingCart;
            }

            return RedirectToAction("Index", new { returnUrl });
        }

        [HttpPost]
        public JsonResult Remove(long id)
        {
            System.Threading.Thread.Sleep(5000);

            string message = string.Empty;
            var _shoppingCart = GetShoppingCart();

            var _shoppingCartItem = _shoppingCart.Itens.Where(x => x.Product.Id == id).FirstOrDefault();
            if (_shoppingCartItem != null)
            {
                _shoppingCart.RemoveItem(_shoppingCartItem);
                Session["ShoppingCart"] = _shoppingCart;

                message = string.Format("{0} removido!", _shoppingCartItem.Product.Name);
            }


            return Json(new { Id = id, Message = message }, JsonRequestBehavior.AllowGet);
        }


        public PartialViewResult Summary()
        {
            var shoppingCart = GetShoppingCart();
            var shoppingCartVM = Mapper.Map<ShoppingCart, ShoppingCartViewModel>(shoppingCart);

            return PartialView(shoppingCartVM);
        }


        public ShoppingCart GetShoppingCart()
        {
            ShoppingCart _shoppingCart = (ShoppingCart)Session["ShoppingCart"];
            if (_shoppingCart == null)
                _shoppingCart = new ShoppingCart();

            return _shoppingCart;
        }
    }
}

ModaMiguelao.Web/Views/ShoppingCart/Index.cshtml
@model ModaMiguelao.Web.ViewModels.ShoppingCartViewModel

@{
    string ReturnUrl = ViewBag.returnUrl;
    string urlRemoveitem = ViewBag.urlRemoveitem;
}

@section styles{
}

@section scripts{
    <script>
        var modal;
        var removedId;
        var urlRemoveitem = '@urlRemoveitem';
    </script>
        
    <script src="~/Scripts/ViewScripts/ShoppingCart.js"></script>
    
}
<h2>Carrinho</h2>
<table class="table table-striped table-condensed table-bordered">
    <thead>
        <tr>

            <th class="text-center">Produto</th>
            <th class="text-center">Quantidade</th>
            <th class="text-center">Preço</th>
            <th class="text-center">Subtotal</th>
            <th class="text-center">Remover</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.Itens)
        {
            <tr id="row-@item.Product.Id">
                <td>@Html.DisplayFor(modelItem => item.Product.Name)</td>
                <td class="text-right">@Html.DisplayFor(modelItem => item.Quantity)</td>
                <td class="text-right">@Html.DisplayFor(modelItem => item.Product.Value)</td>
                <td class="text-right">@Html.DisplayFor(modelItem => item.Value)</td>
                <td class="text-center">
                    @using (Html.BeginForm("Remove", "ShoppingCart"))
                    {
                        @Html.Hidden("id", item.Product.Id)
                        @*@Html.HiddenFor(modelItem => ReturnUrl)*@

                        //TODO - usar as data annotation
                        //TODO - trocar pelo id do item do carrinho
                        <button type="button" class="btn btn-default btn-sm" onclick="removeShoppingCartItem(@item.Product.Id);">
                            <span class="glyphicon glyphicon-remove" style="color:red;" />
                        </button>
                    }
                </td>
            </tr>
        }
    </tbody>
    <tfoot>
        <tr>
            <td colspan="3" class="text-right">Total:</td>
            <td>@Html.DisplayFor(modelItem => modelItem.Total)</td>
            <td></td>
        </tr>
    </tfoot>
</table>

<div>
    <a class="btn btn-primary" href="@ReturnUrl">Continuar Comprando</a>

    @Html.ActionLink("Fechar pedido", "CloseOrder", "Order", null, new { @class = "btn btn-primary" })
</div>

ModaMiguelao.Web/Views/ShoppingCart/Summary.cshtml
@model ModaMiguelao.Web.ViewModels.ShoppingCartViewModel

<div class="navbar-right">
    @Html.ActionLink("Checkout", "Index", "ShoppingCart", new { returnUrl = Request.Url.PathAndQuery }, new { @class = "btn btn-default navbar-btn"} )
</div>
<div class="navbar-text navbar-right">
    <b>Meus Produtos: </b>
    @Model.Itens.Count itens, @Model.Total
</div>
    